<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FJ3LEFB" failures="1" tests="2" name="com.hk.automation.test.runners.TestRunner" time="3.507" errors="0" timestamp="2025-04-06T16:37:06 BST" skipped="0">
  <testcase classname="com.hk.automation.test.runners.TestRunner" name="runScenario" time="3.248"/>
  <testcase classname="com.hk.automation.test.runners.TestRunner" name="runScenario" time="0.259">
    <failure message="expected [APPROVED] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [APPROVED] but found [null]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.hk.automation.test.stepdefs.DBStepDefs.the_decision_should_be(DBStepDefs.java:25)
at âœ½.the decision should be "APPROVED"(file:///D:/WorkSpaces/Practice/test-bdd-framework/src/test/resources/featurefiles/validateApplication.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.hk.automation.test.runners.TestRunner -->
